#cloud-config
package_update: true
package_upgrade: true

packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - nginx
  - certbot
  - python3-certbot-nginx
  - git
  - ufw
  - fail2ban
  - unattended-upgrades

runcmd:
  # Install Docker
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  
  # Configure firewall
  - ufw --force enable
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  
  # Create ghost user and directories
  - useradd -m -s /bin/bash ghost
  - usermod -aG docker ghost
  - mkdir -p /opt/ghost
  - chown -R ghost:ghost /opt/ghost
  
  # Configure fail2ban
  - systemctl enable fail2ban
  - systemctl start fail2ban
  
  # Create swap file (useful for B2s with 4GB RAM)
  - fallocate -l 2G /swapfile
  - chmod 600 /swapfile
  - mkswap /swapfile
  - swapon /swapfile
  - echo '/swapfile none swap sw 0 0' | tee -a /etc/fstab
  
  # Configure automatic security updates
  - dpkg-reconfigure -plow unattended-upgrades
  
  # Performance tuning for B2s VM
  - echo 'vm.swappiness=10' >> /etc/sysctl.conf
  - echo 'vm.vfs_cache_pressure=50' >> /etc/sysctl.conf
  - sysctl -p
  
  # Create marker file
  - touch /var/lib/cloud/instance/user-data-finished