global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    
  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  # Grafana monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    
  # Ghost CMS monitoring (basic HTTP)
  - job_name: 'ghost'
    static_configs:
      - targets: ['ghost:2368']
    metrics_path: /metrics
    params:
      module: [http_2xx]
    
  # Nginx monitoring via logs
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']