global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
        labels:
          service: 'nginx'

  - job_name: 'ghost'
    static_configs:
      - targets: ['ghost:2368']
        labels:
          service: 'ghost'

  # Reframe monitoring disabled due to server crash issue
  # - job_name: 'reframe'
  #   static_configs:
  #     - targets: ['reframe:3000']
  #       labels:
  #         service: 'reframe'