---
- name: Configure Ghost CMS Server
  hosts: ghost-server
  become: yes
  gather_facts: yes
  
  vars_files:
    - vars/main.yml
  
  pre_tasks:
    - name: Wait for cloud-init to complete
      wait_for:
        path: /var/lib/cloud/instance/user-data-finished
        timeout: 600
      
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  
  roles:
    - common
    - docker
    - ghost
    - nginx
    - ssl
    - monitoring
    - backup